# This is a basic workflow to help you get started with Actions

name: Auto increment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  dependabot:
    # Execute this workflow only if dependabot created this PR
    if: ${{ github.actor == 'dependabot[bot]' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up github actions user for upcomming commit
      - name: Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Runs a set of commands using the runners shell
      - name: Checkout dependabot PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}

      # Runs a single command using the runners shell
      - name: Increase patch version
        run: npm version patch -m "[Bot] Increase patch version %s"

      - name: Commit version update
        run: |
          git push origin -u $(git rev-parse --abbrev-ref HEAD)
