name: Precheck plan terrafrom

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, dev ]
    paths:
      - 'infrastructure/**'

jobs:
  plan:
    uses: vent-io/vent-io/.github/workflows/precheck_terraform_plan.yaml@main
    with:
      working_dir: ./infrastructure
      env: ${{ if( github.event.pull_request.base.ref == main, "uat", "dev" ) }}
  print_summary:
    runs-on: ubuntu-latest
    needs: plan
    steps:
      - name: Write summary to pull_request
        uses: thollander/actions-comment-pull-request@v1.4.1
        with:
          message: ${{ needs.plan.outputs.summary }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
