name: Precheck increment label

on:
  pull_request:
    branches: [ $default-branch ]
    types: [opened, reopened, labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    uses: vent-io/vent-io/.github/workflows/precheck_version_label.yaml@main
